### ISSUE TITLE
Why is this way worse with vram?

### ISSUE THREAD

**Issue by GeneralAwareness** [lucidrains/lion-pytorch#10]
I turned off adam and used this and my 15gb ram was eaten alive to the point I had to turn on checkpointing.  The speed was 30% slower than when using adam.  Am I supposed to also turn off xformers?

**Comment by lucidrains** [comment]
think you are comparing an optimized version of adam with lion. if lion survives scrutiny, we can look at adopting the lessons from 8-bit adam to lion, but that will take time

**Comment by GeneralAwareness** [comment]
So, this really is just an open beta then.  Gotcha.

**Comment by lucidrains** [comment]
@GeneralAwareness it takes time for research to be verified and put into practice. sometimes up to half a year to a year.
