### ISSUE TITLE
Add the implementation to official pytorch repo

### ISSUE THREAD

**Issue by crazydonkey200** [lucidrains/lion-pytorch#21]
Thanks for creating this great implementation and for the helpful discussions! I was wondering if there's any plan to add this to the [optimizers](https://github.com/pytorch/pytorch/tree/75cb99e54971c0fdb5f1a6516e3c366af998be43/torch/optim) in the official pytorch codebase. We could refer to this repo, the author's repo, and the paper as references in the docstring, similar to the [lion implementation](https://github.com/keras-team/keras/blob/master/keras/optimizers/lion.py#L28) in the official keras codebase so that more people can benefit from it.

**Comment by lucidrains** [comment]
@crazydonkey200 Hi Chen, I believe someone has already opened an issue but they'd like to wait a bit. I think that makes sense

**Comment by lucidrains** [comment]
We should wait until someone has successfully trained a couple SOTA open sourced models with it out in the wild, imo

**Comment by crazydonkey200** [comment]
Sounds good. Thanks for the pointers!
