### ISSUE TITLE
Add a conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [lucidrains/lion-pytorch#37]
Hi,

It would be useful to have a conda recipe for this package, which would allow for more complex dependency handling.

I am happy to work on this.

Cheers,
Sarthak

**Comment by lucidrains** [comment]
@sarthakpati sure! go right ahead

**Comment by sarthakpati** [comment]
Perfect, thanks. I am on it already: https://github.com/conda-forge/staged-recipes/pull/28303 

Once this gets merged and the conda channels starts building the package, I will put a PR to add conda as an installation option.
