### ISSUE TITLE
AttributeError: module 'trinton.language' has no attribute 'constexpr'

### ISSUE THREAD

**Issue by mlw214** [lucidrains/lion-pytorch#5]
Tried enabling Triton and ran into the above issue. I installed the latest version of Triton on PyPi (1.1.1). Is there a particular version this library is compatible with?

**Comment by lucidrains** [comment]
@mlw214 oh, i think that version may be dated

could you try `pip install trion -U --pre`?

**Comment by mlw214** [comment]
Yep, that fixed it! Thanks for the quick response. May be prudent to call that out in the README that you need the a prerelease of Triton.

**Comment by lucidrains** [comment]
@mlw214 yup, done [here](https://github.com/lucidrains/lion-pytorch/commit/b67f8d8836b4f93db686c60153c671e0e7991725), happy training! do leave your experience with the new optimizer in the discussions

**Comment by lucidrains** [comment]
@mlw214 how did it go?

**Comment by mlw214** [comment]
@lucidrains currently working out a good LR range that doesn't cause the loss to NaN. After a few tries I got one run to finish up without problems. To some context I'm actually throwing this at an object detection problem where I've traditionally used MADGRAD as my optimizer of choice. I'm hoping to have some full experiments done over the next week comparing the two. I'll post to the discussion thread the results, along with more details on the architecture, setup, etc.

**Comment by lucidrains** [comment]
@mlw214 looking forward to it!
